pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

resources:
  containers:
  - container: dotnetcore_arm
    image: huangtingluo/azure-pipelines-agent-eng:arm

  - container: dotnetcore_centos6
    image: huangtingluo/azure-pipelines-agent-eng:centos6

jobs:

################################################################################
- job: build_linux_x64_agent
################################################################################
  displayName: Linux Agent (x64)
  pool:
    vmImage: ubuntu-16.04
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Linux-x64'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

  - script: ls _l1/bin/TestRuns/Test_Base/w/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.164.0
    condition: always()

  - script: ls _l1/bin/TestRuns/Test_Base/w/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.164.0/node_modules
    condition: always()