parameters:
  componentDetection: 'false'
  testLogTitle: 'Non-Windows'

steps:
# Clean
- checkout: self
  clean: true

- script: ./dev.sh testl1
  workingDirectory: src
  displayName: Functional tests
